version: "2"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  web:
    build:
      context: .
    volumes:
      - ./plugins:/var/www/html/plugins/
    ports:
      - 80:80
    links:
      - db
